/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_mpc_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[11] = {12, 1, 0, 7, 2, 3, 4, 5, 9, 10, 11};

/* quad_mpc_cost_ext_cost_e_fun_jac:(i0[12],i1[12])->(o0,o1[12x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=10.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a2=(a3*a1);
  a4=arg[0]? arg[0][3] : 0;
  a5=arg[1]? arg[1][3] : 0;
  a6=(a4-a5);
  a6=(a0*a6);
  a4=(a4-a5);
  a5=(a6*a4);
  a2=(a2+a5);
  a5=arg[0]? arg[0][4] : 0;
  a7=arg[1]? arg[1][4] : 0;
  a8=(a5-a7);
  a8=(a0*a8);
  a5=(a5-a7);
  a7=(a8*a5);
  a2=(a2+a7);
  a7=arg[0]? arg[0][5] : 0;
  a9=arg[1]? arg[1][5] : 0;
  a10=(a7-a9);
  a10=(a0*a10);
  a7=(a7-a9);
  a9=(a10*a7);
  a2=(a2+a9);
  a9=5.;
  a11=arg[0]? arg[0][9] : 0;
  a12=arg[1]? arg[1][9] : 0;
  a13=(a11-a12);
  a13=(a9*a13);
  a11=(a11-a12);
  a12=(a13*a11);
  a2=(a2+a12);
  a12=arg[0]? arg[0][10] : 0;
  a14=arg[1]? arg[1][10] : 0;
  a15=(a12-a14);
  a15=(a9*a15);
  a12=(a12-a14);
  a14=(a15*a12);
  a2=(a2+a14);
  a14=arg[0]? arg[0][11] : 0;
  a16=arg[1]? arg[1][11] : 0;
  a17=(a14-a16);
  a17=(a9*a17);
  a14=(a14-a16);
  a16=(a17*a14);
  a2=(a2+a16);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[1]!=0) res[1][0]=a3;
  a4=(a0*a4);
  a6=(a6+a4);
  if (res[1]!=0) res[1][1]=a6;
  a5=(a0*a5);
  a8=(a8+a5);
  if (res[1]!=0) res[1][2]=a8;
  a0=(a0*a7);
  a10=(a10+a0);
  if (res[1]!=0) res[1][3]=a10;
  a11=(a9*a11);
  a13=(a13+a11);
  if (res[1]!=0) res[1][4]=a13;
  a12=(a9*a12);
  a15=(a15+a12);
  if (res[1]!=0) res[1][5]=a15;
  a9=(a9*a14);
  a17=(a17+a9);
  if (res[1]!=0) res[1][6]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_mpc_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_mpc_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_mpc_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_mpc_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_mpc_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_mpc_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_mpc_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_mpc_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_mpc_cost_ext_cost_e_fun_jac_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int quad_mpc_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quad_mpc_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_mpc_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_mpc_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_mpc_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_mpc_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_mpc_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
