/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BILOOOO_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[23] = {10, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

/* BILOOOO_cost_ext_cost_e_fun_jac_hess:(i0[10],i1[10])->(o0,o1[10],o2[10x10,10nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=100000.;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a2=(a3*a1);
  a4=arg[0]? arg[0][1] : 0;
  a5=arg[1]? arg[1][1] : 0;
  a6=(a4-a5);
  a6=(a0*a6);
  a4=(a4-a5);
  a5=(a6*a4);
  a2=(a2+a5);
  a5=1.0000000000000000e-002;
  a7=arg[0]? arg[0][2] : 0;
  a8=arg[1]? arg[1][2] : 0;
  a9=(a7-a8);
  a9=(a5*a9);
  a7=(a7-a8);
  a8=(a9*a7);
  a2=(a2+a8);
  a8=100.;
  a10=arg[0]? arg[0][3] : 0;
  a11=arg[1]? arg[1][3] : 0;
  a12=(a10-a11);
  a12=(a8*a12);
  a10=(a10-a11);
  a11=(a12*a10);
  a2=(a2+a11);
  a11=arg[0]? arg[0][4] : 0;
  a13=arg[1]? arg[1][4] : 0;
  a14=(a11-a13);
  a14=(a5*a14);
  a11=(a11-a13);
  a13=(a14*a11);
  a2=(a2+a13);
  a13=10.;
  a15=arg[0]? arg[0][5] : 0;
  a16=arg[1]? arg[1][5] : 0;
  a17=(a15-a16);
  a17=(a13*a17);
  a15=(a15-a16);
  a16=(a17*a15);
  a2=(a2+a16);
  a16=arg[0]? arg[0][6] : 0;
  a18=arg[1]? arg[1][6] : 0;
  a19=(a16-a18);
  a19=(a13*a19);
  a16=(a16-a18);
  a18=(a19*a16);
  a2=(a2+a18);
  a18=1.0000000000000001e-005;
  a20=arg[0]? arg[0][7] : 0;
  a21=arg[1]? arg[1][7] : 0;
  a22=(a20-a21);
  a22=(a18*a22);
  a20=(a20-a21);
  a21=(a22*a20);
  a2=(a2+a21);
  a21=1.0000000000000001e-001;
  a23=arg[0]? arg[0][8] : 0;
  a24=arg[1]? arg[1][8] : 0;
  a25=(a23-a24);
  a25=(a21*a25);
  a23=(a23-a24);
  a24=(a25*a23);
  a2=(a2+a24);
  a24=arg[0]? arg[0][9] : 0;
  a26=arg[1]? arg[1][9] : 0;
  a27=(a24-a26);
  a27=(a18*a27);
  a24=(a24-a26);
  a26=(a27*a24);
  a2=(a2+a26);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[1]!=0) res[1][0]=a3;
  a0=(a0*a4);
  a6=(a6+a0);
  if (res[1]!=0) res[1][1]=a6;
  a7=(a5*a7);
  a9=(a9+a7);
  if (res[1]!=0) res[1][2]=a9;
  a8=(a8*a10);
  a12=(a12+a8);
  if (res[1]!=0) res[1][3]=a12;
  a5=(a5*a11);
  a14=(a14+a5);
  if (res[1]!=0) res[1][4]=a14;
  a15=(a13*a15);
  a17=(a17+a15);
  if (res[1]!=0) res[1][5]=a17;
  a13=(a13*a16);
  a19=(a19+a13);
  if (res[1]!=0) res[1][6]=a19;
  a20=(a18*a20);
  a22=(a22+a20);
  if (res[1]!=0) res[1][7]=a22;
  a21=(a21*a23);
  a25=(a25+a21);
  if (res[1]!=0) res[1][8]=a25;
  a18=(a18*a24);
  a27=(a27+a18);
  if (res[1]!=0) res[1][9]=a27;
  a27=200000.;
  if (res[2]!=0) res[2][0]=a27;
  if (res[2]!=0) res[2][1]=a27;
  a27=2.0000000000000000e-002;
  if (res[2]!=0) res[2][2]=a27;
  a18=200.;
  if (res[2]!=0) res[2][3]=a18;
  if (res[2]!=0) res[2][4]=a27;
  a27=20.;
  if (res[2]!=0) res[2][5]=a27;
  if (res[2]!=0) res[2][6]=a27;
  a27=2.0000000000000002e-005;
  if (res[2]!=0) res[2][7]=a27;
  a18=2.0000000000000001e-001;
  if (res[2]!=0) res[2][8]=a18;
  if (res[2]!=0) res[2][9]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int BILOOOO_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BILOOOO_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BILOOOO_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BILOOOO_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BILOOOO_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BILOOOO_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BILOOOO_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void BILOOOO_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BILOOOO_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int BILOOOO_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real BILOOOO_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BILOOOO_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BILOOOO_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BILOOOO_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BILOOOO_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BILOOOO_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
