/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_mpc_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* quad_mpc_dyn_disc_phi_fun:(i0[12],i1[4],i2[12])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=1.0000000000000001e-001;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  a3=(a0+a3);
  a4=-7.2599999999999998e-002;
  a5=arg[1]? arg[1][1] : 0;
  a6=(a4*a5);
  a7=7.2599999999999998e-002;
  a8=arg[1]? arg[1][3] : 0;
  a9=(a7*a8);
  a6=(a6+a9);
  a3=(a3+a6);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a6=arg[0]? arg[0][7] : 0;
  a9=(a1*a6);
  a9=(a3+a9);
  a10=arg[1]? arg[1][0] : 0;
  a4=(a4*a10);
  a11=arg[1]? arg[1][2] : 0;
  a7=(a7*a11);
  a4=(a4+a7);
  a9=(a9+a4);
  if (res[0]!=0) res[0][1]=a9;
  a9=arg[0]? arg[0][2] : 0;
  a4=arg[0]? arg[0][8] : 0;
  a1=(a1*a4);
  a9=(a9+a1);
  a1=-1.5200000000000000e-002;
  a7=(a1*a10);
  a12=1.5200000000000000e-002;
  a13=(a12*a5);
  a7=(a7+a13);
  a1=(a1*a11);
  a7=(a7+a1);
  a12=(a12*a8);
  a7=(a7+a12);
  a9=(a9+a7);
  if (res[0]!=0) res[0][2]=a9;
  a9=4.8800000000000003e-002;
  a7=(a9*a0);
  a12=arg[0]? arg[0][3] : 0;
  a7=(a7+a12);
  a12=1.6000000000000001e-003;
  a12=(a12*a2);
  a7=(a7+a12);
  a12=9.9199999999999997e-002;
  a1=arg[0]? arg[0][9] : 0;
  a13=(a12*a1);
  a7=(a7+a13);
  a13=-5.9999999999999995e-004;
  a14=(a13*a5);
  a15=5.9999999999999995e-004;
  a16=(a15*a8);
  a14=(a14+a16);
  a7=(a7+a14);
  if (res[0]!=0) res[0][3]=a7;
  a7=-4.8800000000000003e-002;
  a14=(a7*a3);
  a16=arg[0]? arg[0][4] : 0;
  a14=(a14+a16);
  a16=-1.6000000000000001e-003;
  a16=(a16*a6);
  a14=(a14+a16);
  a16=arg[0]? arg[0][10] : 0;
  a17=(a12*a16);
  a14=(a14+a17);
  a15=(a15*a10);
  a13=(a13*a11);
  a15=(a15+a13);
  a14=(a14+a15);
  if (res[0]!=0) res[0][4]=a14;
  a14=arg[0]? arg[0][5] : 0;
  a15=arg[0]? arg[0][11] : 0;
  a12=(a12*a15);
  a14=(a14+a12);
  a12=1.0600000000000000e-002;
  a13=(a12*a10);
  a17=(a12*a5);
  a13=(a13+a17);
  a17=(a12*a11);
  a13=(a13+a17);
  a12=(a12*a8);
  a13=(a13+a12);
  a14=(a14+a13);
  if (res[0]!=0) res[0][5]=a14;
  a14=-1.4512000000000000e+000;
  a13=(a14*a5);
  a12=1.4512000000000000e+000;
  a17=(a12*a8);
  a13=(a13+a17);
  a13=(a2+a13);
  if (res[0]!=0) res[0][6]=a13;
  a14=(a14*a10);
  a12=(a12*a11);
  a14=(a14+a12);
  a14=(a6+a14);
  if (res[0]!=0) res[0][7]=a14;
  a14=-3.0490000000000000e-001;
  a12=(a14*a10);
  a13=3.0490000000000000e-001;
  a17=(a13*a5);
  a12=(a12+a17);
  a14=(a14*a11);
  a12=(a12+a14);
  a13=(a13*a8);
  a12=(a12+a13);
  a4=(a4+a12);
  if (res[0]!=0) res[0][8]=a4;
  a4=9.7340000000000004e-001;
  a4=(a4*a0);
  a9=(a9*a2);
  a4=(a4+a9);
  a9=9.8460000000000003e-001;
  a1=(a9*a1);
  a4=(a4+a1);
  a1=-2.3599999999999999e-002;
  a2=(a1*a5);
  a0=2.3599999999999999e-002;
  a12=(a0*a8);
  a2=(a2+a12);
  a4=(a4+a2);
  if (res[0]!=0) res[0][9]=a4;
  a4=-9.7340000000000004e-001;
  a4=(a4*a3);
  a7=(a7*a6);
  a4=(a4+a7);
  a16=(a9*a16);
  a4=(a4+a16);
  a0=(a0*a10);
  a1=(a1*a11);
  a0=(a0+a1);
  a4=(a4+a0);
  if (res[0]!=0) res[0][10]=a4;
  a9=(a9*a15);
  a15=2.1070000000000000e-001;
  a10=(a15*a10);
  a5=(a15*a5);
  a10=(a10+a5);
  a11=(a15*a11);
  a10=(a10+a11);
  a15=(a15*a8);
  a10=(a10+a15);
  a9=(a9+a10);
  if (res[0]!=0) res[0][11]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_mpc_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_mpc_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_mpc_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_mpc_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_mpc_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_mpc_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_mpc_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_mpc_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_mpc_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_mpc_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_mpc_dyn_disc_phi_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_mpc_dyn_disc_phi_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_mpc_dyn_disc_phi_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_mpc_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_mpc_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_mpc_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
