/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {0, 2, 5};
static const casadi_int casadi_s1[3] = {1, 3, 6};
static const casadi_int casadi_s2[3] = {0, 3, 5};
static const casadi_int casadi_s3[3] = {2, 4, 7};
static const casadi_int casadi_s4[19] = {8, 8, 0, 0, 0, 0, 0, 0, 3, 5, 8, 5, 6, 7, 5, 7, 5, 6, 7};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[16] = {8, 5, 0, 2, 5, 6, 7, 8, 5, 6, 5, 6, 7, 3, 6, 7};
static const casadi_int casadi_s10[8] = {0, 5, 0, 0, 0, 0, 0, 0};

/* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess:(i0[6],i1[2],i2[5],i3[],i4[])->(o0[5],o1[8x5,8nz],o2[8x8,8nz],o3[0x5],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+20, *w21=w+28, w22, w23, w24, *w27=w+37, *w28=w+40, *w30=w+43, *w31=w+45, *w34=w+47, w35, w36, w37, *w39=w+55;
  /* #0: @0 = 0.28 */
  w0 = 2.8000000000000003e-001;
  /* #1: @1 = 0.05 */
  w1 = 5.0000000000000003e-002;
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #4: @0 = (@0-@3) */
  w0 -= w3;
  /* #5: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: @5 = 0.006 */
  w5 = 6.0000000000000001e-003;
  /* #8: @6 = (@5*@2) */
  w6  = (w5*w2);
  /* #9: @7 = (@6*@2) */
  w7  = (w6*w2);
  /* #10: @4 = (@4-@7) */
  w4 -= w7;
  /* #11: @7 = 0.011 */
  w7 = 1.0999999999999999e-002;
  /* #12: @8 = 5 */
  w8 = 5.;
  /* #13: @9 = (@8*@2) */
  w9  = (w8*w2);
  /* #14: @9 = tanh(@9) */
  w9 = tanh( w9 );
  /* #15: @10 = (@7*@9) */
  w10  = (w7*w9);
  /* #16: @4 = (@4-@10) */
  w4 -= w10;
  /* #17: @10 = 0.043 */
  w10 = 4.2999999999999997e-002;
  /* #18: @10 = (@4/@10) */
  w10  = (w4/w10);
  /* #19: output[0][0] = @10 */
  if (res[0]) res[0][0] = w10;
  /* #20: @10 = 15.5 */
  w10 = 1.5500000000000000e+001;
  /* #21: @11 = (@10*@2) */
  w11  = (w10*w2);
  /* #22: @12 = (@11*@2) */
  w12  = (w11*w2);
  /* #23: @13 = input[0][5] */
  w13 = arg[0] ? arg[0][5] : 0;
  /* #24: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #25: @15 = 0.5 */
  w15 = 5.0000000000000000e-001;
  /* #26: @16 = (@15*@13) */
  w16  = (w15*w13);
  /* #27: @17 = sin(@16) */
  w17 = sin( w16 );
  /* #28: @18 = (@4*@17) */
  w18  = (w4*w17);
  /* #29: @19 = 0.043 */
  w19 = 4.2999999999999997e-002;
  /* #30: @18 = (@18/@19) */
  w18 /= w19;
  /* #31: @14 = (@14+@18) */
  w14 += w18;
  /* #32: output[0][1] = @14 */
  if (res[0]) res[0][1] = w14;
  /* #33: @14 = input[0][1] */
  w14 = arg[0] ? arg[0][1] : 0;
  /* #34: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #35: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #36: output[0][4] = @13 */
  if (res[0]) res[0][4] = w13;
  /* #37: @20 = zeros(8x5,8nz) */
  casadi_clear(w20, 8);
  /* #38: @14 = 23.2558 */
  w14 = 2.3255813953488374e+001;
  /* #39: @21 = ones(8x1,6nz) */
  casadi_fill(w21, 6, 1.);
  /* #40: {NULL, NULL, NULL, @18, NULL, @19, NULL, NULL} = vertsplit(@21) */
  w18 = w21[3];
  w19 = w21[5];
  /* #41: @22 = (@5*@19) */
  w22  = (w5*w19);
  /* #42: @22 = (@2*@22) */
  w22  = (w2*w22);
  /* #43: @23 = (@6*@19) */
  w23  = (w6*w19);
  /* #44: @22 = (@22+@23) */
  w22 += w23;
  /* #45: @22 = (-@22) */
  w22 = (- w22 );
  /* #46: @23 = (@1*@19) */
  w23  = (w1*w19);
  /* #47: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #48: @22 = (@22-@23) */
  w22 -= w23;
  /* #49: @23 = 1 */
  w23 = 1.;
  /* #50: @24 = sq(@9) */
  w24 = casadi_sq( w9 );
  /* #51: @23 = (@23-@24) */
  w23 -= w24;
  /* #52: @24 = (@8*@19) */
  w24  = (w8*w19);
  /* #53: @23 = (@23*@24) */
  w23 *= w24;
  /* #54: @23 = (@7*@23) */
  w23  = (w7*w23);
  /* #55: @22 = (@22-@23) */
  w22 -= w23;
  /* #56: @23 = (@14*@22) */
  w23  = (w14*w22);
  /* #57: @24 = (@10*@19) */
  w24  = (w10*w19);
  /* #58: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #59: @19 = (@11*@19) */
  w19  = (w11*w19);
  /* #60: @24 = (@24+@19) */
  w24 += w19;
  /* #61: @24 = (@13*@24) */
  w24  = (w13*w24);
  /* #62: @19 = 23.2558 */
  w19 = 2.3255813953488374e+001;
  /* #63: @22 = (@17*@22) */
  w22  = (w17*w22);
  /* #64: @22 = (@19*@22) */
  w22  = (w19*w22);
  /* #65: @24 = (@24+@22) */
  w24 += w22;
  /* #66: @25 = 00 */
  /* #67: @26 = 00 */
  /* #68: @27 = vertcat(@23, @24, @18, @25, @26) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w18;
  /* #69: @28 = @27[:3] */
  for (rr=w28, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #70: (@20[0, 2, 5] = @28) */
  for (cii=casadi_s0, rr=w20, ss=w28; cii!=casadi_s0+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #71: @23 = ones(8x1,1nz) */
  w23 = 1.;
  /* #72: {NULL, NULL, NULL, NULL, NULL, NULL, @24, NULL} = vertsplit(@23) */
  w24 = w23;
  /* #73: @23 = (@0*@24) */
  w23  = (w0*w24);
  /* #74: @14 = (@14*@23) */
  w14 *= w23;
  /* #75: @23 = (@17*@23) */
  w23  = (w17*w23);
  /* #76: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #77: @25 = 00 */
  /* #78: @26 = 00 */
  /* #79: @28 = vertcat(@14, @23, @25, @24, @26) */
  rr=w28;
  *rr++ = w14;
  *rr++ = w23;
  *rr++ = w24;
  /* #80: @27 = @28[:3] */
  for (rr=w27, ss=w28+0; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #81: (@20[1, 3, 6] = @27) */
  for (cii=casadi_s1, rr=w20, ss=w27; cii!=casadi_s1+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #82: @25 = 00 */
  /* #83: @14 = ones(8x1,1nz) */
  w14 = 1.;
  /* #84: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @23} = vertsplit(@14) */
  w23 = w14;
  /* #85: @12 = (@12*@23) */
  w12 *= w23;
  /* #86: @14 = cos(@16) */
  w14 = cos( w16 );
  /* #87: @24 = (@15*@23) */
  w24  = (w15*w23);
  /* #88: @14 = (@14*@24) */
  w14 *= w24;
  /* #89: @14 = (@4*@14) */
  w14  = (w4*w14);
  /* #90: @19 = (@19*@14) */
  w19 *= w14;
  /* #91: @12 = (@12+@19) */
  w12 += w19;
  /* #92: @26 = 00 */
  /* #93: @29 = 00 */
  /* #94: @30 = vertcat(@25, @12, @26, @29, @23) */
  rr=w30;
  *rr++ = w12;
  *rr++ = w23;
  /* #95: @31 = @30[:2] */
  for (rr=w31, ss=w30+0; ss!=w30+2; ss+=1) *rr++ = *ss;
  /* #96: (@20[4:10:3] = @31) */
  for (rr=w20+4, ss=w31; rr!=w20+10; rr+=3) *rr = *ss++;
  /* #97: output[1][0] = @20 */
  casadi_copy(w20, 8, res[1]);
  /* #98: @20 = zeros(8x8,8nz) */
  casadi_clear(w20, 8);
  /* #99: @25 = 00 */
  /* #100: @26 = 00 */
  /* #101: @29 = 00 */
  /* #102: @32 = 00 */
  /* #103: @33 = 00 */
  /* #104: @34 = input[2][0] */
  casadi_copy(arg[2], 5, w34);
  /* #105: {@12, @23, NULL, NULL, NULL} = vertsplit(@34) */
  w12 = w34[0];
  w23 = w34[1];
  /* #106: @13 = (@13*@23) */
  w13 *= w23;
  /* #107: @21 = ones(8x1,6nz) */
  casadi_fill(w21, 6, 1.);
  /* #108: {NULL, NULL, NULL, NULL, NULL, @19, NULL, NULL} = vertsplit(@21) */
  w19 = w21[5];
  /* #109: @14 = (@10*@19) */
  w14  = (w10*w19);
  /* #110: @24 = (@13*@14) */
  w24  = (w13*w14);
  /* #111: @13 = (@13*@19) */
  w13 *= w19;
  /* #112: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #113: @24 = (@24+@13) */
  w24 += w13;
  /* #114: @13 = 23.2558 */
  w13 = 2.3255813953488374e+001;
  /* #115: @13 = (@13*@23) */
  w13 *= w23;
  /* #116: @17 = (@17*@13) */
  w17 *= w13;
  /* #117: @18 = 23.2558 */
  w18 = 2.3255813953488374e+001;
  /* #118: @18 = (@18*@12) */
  w18 *= w12;
  /* #119: @17 = (@17+@18) */
  w17 += w18;
  /* #120: @18 = (@7*@17) */
  w18  = (w7*w17);
  /* #121: @12 = (2.*@9) */
  w12 = (2.* w9 );
  /* #122: @22 = 1 */
  w22 = 1.;
  /* #123: @35 = sq(@9) */
  w35 = casadi_sq( w9 );
  /* #124: @22 = (@22-@35) */
  w22 -= w35;
  /* #125: @35 = (@8*@19) */
  w35  = (w8*w19);
  /* #126: @22 = (@22*@35) */
  w22 *= w35;
  /* #127: @12 = (@12*@22) */
  w12 *= w22;
  /* #128: @18 = (@18*@12) */
  w18 *= w12;
  /* #129: @18 = (@8*@18) */
  w18  = (w8*w18);
  /* #130: @24 = (@24+@18) */
  w24 += w18;
  /* #131: @18 = (@5*@19) */
  w18  = (w5*w19);
  /* #132: @12 = (@17*@18) */
  w12  = (w17*w18);
  /* #133: @24 = (@24-@12) */
  w24 -= w12;
  /* #134: @12 = (@17*@19) */
  w12  = (w17*w19);
  /* #135: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #136: @24 = (@24-@12) */
  w24 -= w12;
  /* #137: @12 = (@1*@19) */
  w12  = (w1*w19);
  /* #138: @35 = (@17*@12) */
  w35  = (w17*w12);
  /* #139: @35 = (-@35) */
  w35 = (- w35 );
  /* #140: @36 = cos(@16) */
  w36 = cos( w16 );
  /* #141: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #142: @37 = (@6*@19) */
  w37  = (w6*w19);
  /* #143: @18 = (@18+@37) */
  w18 += w37;
  /* #144: @18 = (-@18) */
  w18 = (- w18 );
  /* #145: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #146: @18 = (@18-@12) */
  w18 -= w12;
  /* #147: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #148: @18 = (@18-@22) */
  w18 -= w22;
  /* #149: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #150: @18 = (@36*@18) */
  w18  = (w36*w18);
  /* #151: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #152: @14 = (@2*@14) */
  w14  = (w2*w14);
  /* #153: @19 = (@11*@19) */
  w19  = (w11*w19);
  /* #154: @14 = (@14+@19) */
  w14 += w19;
  /* #155: @14 = (@23*@14) */
  w14  = (w23*w14);
  /* #156: @18 = (@18+@14) */
  w18 += w14;
  /* #157: @27 = vertcat(@25, @26, @29, @32, @33, @24, @35, @18) */
  rr=w27;
  *rr++ = w24;
  *rr++ = w35;
  *rr++ = w18;
  /* #158: @28 = @27[:3] */
  for (rr=w28, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #159: (@20[0, 3, 5] = @28) */
  for (cii=casadi_s2, rr=w20, ss=w28; cii!=casadi_s2+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #160: @25 = 00 */
  /* #161: @26 = 00 */
  /* #162: @29 = 00 */
  /* #163: @32 = 00 */
  /* #164: @33 = 00 */
  /* #165: @24 = ones(8x1,1nz) */
  w24 = 1.;
  /* #166: {NULL, NULL, NULL, NULL, NULL, NULL, @35, NULL} = vertsplit(@24) */
  w35 = w24;
  /* #167: @17 = (@17*@35) */
  w17 *= w35;
  /* #168: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #169: @17 = (-@17) */
  w17 = (- w17 );
  /* #170: @38 = 00 */
  /* #171: @35 = (@0*@35) */
  w35  = (w0*w35);
  /* #172: @35 = (@13*@35) */
  w35  = (w13*w35);
  /* #173: @36 = (@36*@35) */
  w36 *= w35;
  /* #174: @36 = (@15*@36) */
  w36  = (w15*w36);
  /* #175: @31 = vertcat(@25, @26, @29, @32, @33, @17, @38, @36) */
  rr=w31;
  *rr++ = w17;
  *rr++ = w36;
  /* #176: @30 = @31[:2] */
  for (rr=w30, ss=w31+0; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #177: (@20[1:11:5] = @30) */
  for (rr=w20+1, ss=w30; rr!=w20+11; rr+=5) *rr = *ss++;
  /* #178: @25 = 00 */
  /* #179: @26 = 00 */
  /* #180: @29 = 00 */
  /* #181: @32 = 00 */
  /* #182: @33 = 00 */
  /* #183: @17 = ones(8x1,1nz) */
  w17 = 1.;
  /* #184: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @36} = vertsplit(@17) */
  w36 = w17;
  /* #185: @23 = (@23*@36) */
  w23 *= w36;
  /* #186: @11 = (@11*@23) */
  w11 *= w23;
  /* #187: @23 = (@2*@23) */
  w23  = (w2*w23);
  /* #188: @10 = (@10*@23) */
  w10 *= w23;
  /* #189: @11 = (@11+@10) */
  w11 += w10;
  /* #190: @10 = 1 */
  w10 = 1.;
  /* #191: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #192: @10 = (@10-@9) */
  w10 -= w9;
  /* #193: @9 = cos(@16) */
  w9 = cos( w16 );
  /* #194: @36 = (@15*@36) */
  w36  = (w15*w36);
  /* #195: @9 = (@9*@36) */
  w9 *= w36;
  /* #196: @9 = (@13*@9) */
  w9  = (w13*w9);
  /* #197: @7 = (@7*@9) */
  w7 *= w9;
  /* #198: @10 = (@10*@7) */
  w10 *= w7;
  /* #199: @8 = (@8*@10) */
  w8 *= w10;
  /* #200: @11 = (@11-@8) */
  w11 -= w8;
  /* #201: @6 = (@6*@9) */
  w6 *= w9;
  /* #202: @11 = (@11-@6) */
  w11 -= w6;
  /* #203: @2 = (@2*@9) */
  w2 *= w9;
  /* #204: @5 = (@5*@2) */
  w5 *= w2;
  /* #205: @11 = (@11-@5) */
  w11 -= w5;
  /* #206: @3 = (@3*@9) */
  w3 *= w9;
  /* #207: @1 = (@1*@3) */
  w1 *= w3;
  /* #208: @11 = (@11-@1) */
  w11 -= w1;
  /* #209: @0 = (@0*@9) */
  w0 *= w9;
  /* #210: @4 = (@4*@13) */
  w4 *= w13;
  /* #211: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #212: @16 = (@16*@36) */
  w16 *= w36;
  /* #213: @4 = (@4*@16) */
  w4 *= w16;
  /* #214: @15 = (@15*@4) */
  w15 *= w4;
  /* #215: @15 = (-@15) */
  w15 = (- w15 );
  /* #216: @28 = vertcat(@25, @26, @29, @32, @33, @11, @0, @15) */
  rr=w28;
  *rr++ = w11;
  *rr++ = w0;
  *rr++ = w15;
  /* #217: @27 = @28[:3] */
  for (rr=w27, ss=w28+0; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #218: (@20[2, 4, 7] = @27) */
  for (cii=casadi_s3, rr=w20, ss=w27; cii!=casadi_s3+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #219: @39 = @20' */
  casadi_trans(w20,casadi_s4, w39, casadi_s4, iw);
  /* #220: output[2][0] = @39 */
  casadi_copy(w39, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s9;
    case 2: return casadi_s4;
    case 3: return casadi_s10;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 63;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
