/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_model_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[13] = {4, 4, 0, 0, 2, 3, 6, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s4[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[6] = {4, 1, 0, 2, 2, 3};

/* sim_model_impl_dae_fun_jac_x_xdot_u:(i0[4],i1[4],i2,i3[],i4[])->(o0[4],o1[4x4,6nz],o2[4x4,4nz],o3[4x1,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a0-a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=-8.0000000000000016e-002;
  a2=arg[0]? arg[0][1] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a5=casadi_sq(a0);
  a6=(a4*a5);
  a7=arg[2]? arg[2][0] : 0;
  a6=(a6+a7);
  a8=9.8100000000000009e-001;
  a9=cos(a2);
  a10=(a8*a9);
  a11=(a10*a3);
  a6=(a6+a11);
  a11=1.1000000000000001e+000;
  a12=1.0000000000000001e-001;
  a13=casadi_sq(a9);
  a13=(a12*a13);
  a11=(a11-a13);
  a6=(a6/a11);
  a13=arg[1]? arg[1][2] : 0;
  a13=(a6-a13);
  if (res[0]!=0) res[0][2]=a13;
  a13=(a1*a9);
  a14=(a13*a3);
  a15=casadi_sq(a0);
  a16=(a14*a15);
  a17=(a7*a9);
  a16=(a16+a17);
  a17=(a8*a3);
  a16=(a16+a17);
  a17=9.8100000000000005e+000;
  a18=(a17*a3);
  a16=(a16+a18);
  a18=8.0000000000000004e-001;
  a19=(a18*a11);
  a16=(a16/a19);
  a20=arg[1]? arg[1][3] : 0;
  a20=(a16-a20);
  if (res[0]!=0) res[0][3]=a20;
  a20=cos(a2);
  a21=(a1*a20);
  a5=(a5*a21);
  a10=(a10*a20);
  a2=sin(a2);
  a21=(a8*a2);
  a21=(a3*a21);
  a10=(a10-a21);
  a5=(a5+a10);
  a5=(a5/a11);
  a6=(a6/a11);
  a10=(a9+a9);
  a10=(a10*a2);
  a12=(a12*a10);
  a6=(a6*a12);
  a5=(a5-a6);
  if (res[1]!=0) res[1][0]=a5;
  a13=(a13*a20);
  a1=(a1*a2);
  a3=(a3*a1);
  a13=(a13-a3);
  a15=(a15*a13);
  a7=(a7*a2);
  a15=(a15-a7);
  a8=(a8*a20);
  a15=(a15+a8);
  a17=(a17*a20);
  a15=(a15+a17);
  a15=(a15/a19);
  a16=(a16/a19);
  a18=(a18*a12);
  a16=(a16*a18);
  a15=(a15-a16);
  if (res[1]!=0) res[1][1]=a15;
  a15=1.;
  if (res[1]!=0) res[1][2]=a15;
  if (res[1]!=0) res[1][3]=a15;
  a15=(a0+a0);
  a4=(a4*a15);
  a4=(a4/a11);
  if (res[1]!=0) res[1][4]=a4;
  a0=(a0+a0);
  a14=(a14*a0);
  a14=(a14/a19);
  if (res[1]!=0) res[1][5]=a14;
  a14=-1.;
  if (res[2]!=0) res[2][0]=a14;
  if (res[2]!=0) res[2][1]=a14;
  if (res[2]!=0) res[2][2]=a14;
  if (res[2]!=0) res[2][3]=a14;
  a11=(1./a11);
  if (res[3]!=0) res[3][0]=a11;
  a9=(a9/a19);
  if (res[3]!=0) res[3][1]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_model_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_model_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_model_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_model_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_model_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_model_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_model_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_model_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_model_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_model_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real sim_model_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_model_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_model_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_model_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_model_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_model_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
